version: '3'
volumes:
  db_data:
services:
  db:
    image: mariadb:10.11.4
    container_name: course-202307-php-rwd-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: 'laravel'
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: '1234'
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
  backend:
    container_name: course-202307-php-rwd-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./backend/app:/api/app
      - ./backend/database:/api/database
      - ./backend/config:/api/config
      - ./backend/routes:/api/routes
      - ./backend/storage:/api/storage
  frontend:
    container_name: course-202307-php-rwd-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes: 
      - ./frontend:/usr/share/nginx/html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80